name: artifact
on: push

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello-world > hello.txt
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-test
        paths: ./hello.txt

  download-artifacts:
    runs-on: ubuntu-latest
    needs: [upload-artifacts]
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact-test
        path: ./
    - name: check
      run: cat hello.txt